### ISSUE TITLE
ATOM版本2.5.1.不能使用了.

### ISSUE THREAD

**Issue by thewkgithub** [tychenjiajun/qcloud-uploader#4]
不知道作者是否没有时间做这个事情了.如果真的没时间的话,能否告知如何修改与发布.因为没有做过ATOM的插件,我想给修改好,提交一下,支持最新的OSS SDK.

**Comment by tychenjiajun** [comment]
@thewkgithub 是因为atom的问题还是sdk的问题呢？

**Comment by tychenjiajun** [comment]
@thewkgithub  修改请fork，并clone到本地，修改后提交pull request，不要修改版本号
如需相关接口文档请参阅[Electron文档](https://electronjs.org/docs)和[Node文档](https://nodejs.org/api/documentation.html)

**Comment by tychenjiajun** [comment]
@thewkgithub OSS SDK已经更新了，你可以修改并提出pull request。

**Comment by tychenjiajun** [comment]
和 #3 重复，关闭
